modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="morestructures"
version="1.3.0"
displayName="MoreStructures"
displayURL="https://modrinth.com"
credits="Lhas20"
authors="Ender Studio"
description="The more structure mod. "

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.morestructures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration